server:
  port: 8081
spring:
  sql.init.mode: always
  datasource:
    url: jdbc:mysql://localhost:3333/edgeDB
    username: dfii
    password: Dfii1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # uncomment the below lines to view sql output in console
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: create
